repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: fix-byte-order-marker
    - id: destroyed-symlinks
    - id: fix-encoding-pragma
      args: ["--remove"]
    - id: mixed-line-ending
    - id: name-tests-test
      args: ["--pytest-test-first"]
    - id: pretty-format-json
      args: ["--autofix", "--no-ensure-ascii"]
      exclude: ".ipynb"

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.8
  hooks:
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]
